### ISSUE TITLE
State transition doesn't work when going to the state where it came from

### ISSUE THREAD

**Issue by ratozumbi** [kubecz3k/FiniteStateMachine#10]
When you have a transition pointing to the state where it came from, neither the `transitionCondition` returning true or the `accomplish()` call will make the state `exit()` .

**Comment by kubecz3k** [comment]
From your description you are talking about such situation:
```
   +----------+
   |SOME_STATE|
   +-+--------+
     ^       |
     |       |
     |       |
     |       v
+------------+---+
|SOME_TRANSITION |
+----------------+

```
If so then this is correct behavior, state is not exiting since there is no state change

**Comment by kubecz3k** [comment]
If you need to reset state in such way please make it manually with some custom reset() function. Also I would just implement the condition check inside state logic in such case.
