### ISSUE TITLE
Member 'name' already exists as a class property

### ISSUE THREAD

**Issue by MrGreenTea** [kubecz3k/FiniteStateMachine#12]
When I try to run a scene with a FSM2D node I get the above error.
This is probably because GraphNode.gd has a name variable. If you look at the bottom here: https://godotengine.org/article/dev-snapshot-godot-3-0-rc-1 you can see that they warn us about that.

Would be awesome if you come around to fixing that.

**Comment by kubecz3k** [comment]
Fixed by 6492c5302475bf92ed84023cf0c615c202185389
