### ISSUE TITLE
"a" characters have been printed whenever I touch the tool graph

### ISSUE THREAD

**Issue by salvob41** [kubecz3k/FiniteStateMachine#17]
As showing in this picture (taken from the issue #16 ) every-time I touch anything from the tool view, it prints an "a" character on the left of the window. One for each line, and it goes on and on. 
Is it just me? 

I am using Godot3.0.2 in a macOSX 10.13.4

![image](https://user-images.githubusercontent.com/6097015/39087338-c7d80554-459f-11e8-9dca-a73b323bf215.png)

**Comment by kubecz3k** [comment]
Thank you for the report!

**Comment by tavurth** [comment]
This is still present 3.0.6.stable.official.8314054, ubuntu

**Comment by kubecz3k** [comment]
I think the version on the assetstore is not updated

**Comment by salvob41** [comment]
do you plan to do it soon ?
