### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by doradoro** [kubecz3k/FiniteStateMachine#38]
Are you planning updates?

I installed it in godot 3.3.2 and it doesnt seem to work anymore

**Comment by kubecz3k** [comment]
Hey, I just updated the plugin and it should now work with 3.3.2

**Comment by doradoro** [comment]
The Asset Library version still seems to be old but its probably due the update process.. isnt it?

**Comment by kubecz3k** [comment]
I updated it right here on github, so I would suggest to get it via download zip button:
![image](https://user-images.githubusercontent.com/6129594/125308905-99e8b700-e331-11eb-95d8-705ed792ad59.png)
I will update on asset library later this week
