### ISSUE TITLE
Automatically add FSM nodes to an "fsm" group?

### ISSUE THREAD

**Issue by radicaled** [kubecz3k/FiniteStateMachine#5]
How can I add all FSM nodes (FSM2D, FSMControl, FSM3D) to an "fsm" group manually? What file or scene in the addon should I edit?

I'm trying to do some automatic debugging UI stuff in my game, and I'd like to be able to quickly find all FSMs for a node so I can grab / display their state without having to hardcore references. EG: I have a "StateDebug" node that's currently hardcoded, but I want to make it dynamically find the FSMs under its parent node.

**Comment by kubecz3k** [comment]
Helllo, to add all FSMs nodes to group use something like `add_to_group("FSM")` in init() method of fsm.gd. I think I will make those nodes part of a group by default. Also it's quite probable I will work on some kind of debug visualisation in next week.

**Comment by kubecz3k** [comment]
Also if you will make any changes in FSM.gd make sure all the scenes where you have your fms are closed. Godot is trying to reload all the changes instantly and quite often in this situation information about graph positions is lost.

**Comment by radicaled** [comment]
Thanks, that is exactly what I needed to know!

>  I think I will make those nodes part of a group by default. 

I'll leave this issue open then so you can commit against it then.

**Comment by kubecz3k** [comment]
Hey, in newest commit all fsms should be in FSM group. Also I have added some initial code for rendering debug info in the form of current state ID  and previously used transition:
![fsm_debug](https://user-images.githubusercontent.com/6129594/27295596-c1bb685a-551d-11e7-90b7-792fc55c096d.png)

**Comment by kubecz3k** [comment]
solved by https://github.com/kubecz3k/FiniteStateMachine/commit/7e5dadeb7b5d21d14f28b28559182ac2dcd5d132
