### ISSUE TITLE
Godot 3.0 support

### ISSUE THREAD

**Issue by LLafodog** [kubecz3k/FiniteStateMachine#7]
Hi, 
First of all, thanks for the amazing job, this addon is from far the best I could expect ! 

Now that godot engine is evolving into version 3.0 and a lot of the API is changing, I tried to use the FSM in a v3.0 project; where it obviously failed. 

Have you considered updating it to the newest version of godot engine ? Would you like some help in any way ? 

Thanks again !

**Comment by kubecz3k** [comment]
Hello @LLafodog this plugin is being updated constantly since some time to catch up with current Godot master branch. You will need to compile Godot yourself (since api is still evolving and there were already changes since alpha1), and you will need to download plugin from here (github).

**Comment by kubecz3k** [comment]
I have submitted version compatible with Godot 3 to asset store today. Hopefully there will be no more api breakage before beta
